-- CreateEnum
CREATE TYPE "EMPLOYMENT_STATUS" AS ENUM ('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERNSHIP');

-- AlterTable
ALTER TABLE "employees" ADD COLUMN     "employmentEndDate" TIMESTAMP(3),
ADD COLUMN     "employmentStatus" "EMPLOYMENT_STATUS" NOT NULL DEFAULT 'FULL_TIME';
